# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=25)),
                ('nome', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_com_hora', models.DateTimeField(auto_now=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfrequencia.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_turma', models.IntegerField()),
                ('nome', models.CharField(max_length=20)),
                ('horario', models.TimeField(auto_now=True)),
                ('data_inicio', models.DateField(auto_now=True)),
                ('data_final', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='id_turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfrequencia.Turma'),
        ),
    ]
