# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfrequencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='data_final',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='turma',
            name='horario',
            field=models.TimeField(),
        ),
    ]
