# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfrequencia', '0002_auto_20170202_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='data_com_hora',
            field=models.DateTimeField(),
        ),
    ]
