# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfrequencia', '0003_auto_20170202_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='faltas',
            field=models.IntegerField(default=0),
        ),
    ]
