# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfrequencia', '0004_frequencia_faltas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='data_com_hora',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
