# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfrequencia', '0006_auto_20170206_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='faltas',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
